name: Build and Deploy

on:
  push:
    branches:
      - main  # or master, based on your default branch

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: Start the server using PM2
      run: pm2 start server.js --name "simple-node-server" || pm2 restart "simple-node-server"

