name: Deploy to Ubuntu Server

on:
  workflow_dispatch:
    inputs:
      Test:
        description: 'Test'
        type: string
        required: false
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: Linux
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.SERVER_PORT }}
        
    - name: Ping server
      run: |
        ping -c 4 ${{ secrets.SERVER_HOST }}
        hostname