jobs:
    deploy:
      runs-on: Linux
      steps:
      - name: Checkout code
        uses: actions/checkout@v2
  
      - name: Deploy to server
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > deploy_key
          chmod 600 deploy_key
          ssh -i deploy_key user@your_server_ip "your deploy commands here"
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  
